import test from 'node:test';
import assert from 'node:assert/strict';
import sharp from 'sharp';
import {fixture,notice,testPassword} from './helpers.mjs';
import {contentPath,mediaPath,validateContent} from '../netlify/lib/admin-content.mjs';
import {SESSION_SECONDS,createAuth,configuration,withWriteLock} from '../netlify/lib/admin-security.mjs';
import {randomBytes} from 'node:crypto';

test('Login correct; Secure HttpOnly Strict cookie; no credentials in response',async()=>{
  const f=await fixture(),response=await f.request('login',{method:'POST',data:{email:f.env.ADMIN_EMAIL,password:testPassword}});
  assert.equal(response.status,200);const cookie=response.headers.get('set-cookie');
  for(const part of ['__Host-parafia_admin=','HttpOnly','Secure','SameSite=Strict','Path=/','Max-Age=14400'])assert.ok(cookie.includes(part));
  const body=await response.text();for(const secret of [testPassword,f.env.GITHUB_TOKEN,f.env.SESSION_SECRET,f.env.ADMIN_PASSWORD_HASH])assert.ok(!body.includes(secret));
  assert.equal(f.github.calls.length,0);
});
for(const [name,email,password] of [['wrong password','admin@example.test','incorrect'],['wrong email','other@example.test',testPassword]])test(`Login: ${name}`,async()=>{const f=await fixture();assert.equal((await f.request('login',{method:'POST',data:{email,password}})).status,401);});
for(const path of ['session/me','content?collection=ogloszenia','media?path=assets/uploads/a.jpg'])test(`Unauthenticated read: ${path}`,async()=>{const f=await fixture();assert.equal((await f.request(path)).status,401);assert.equal(f.github.calls.length,0);});
for(const [path,method] of [['content','POST'],['content','DELETE'],['upload','POST'],['logout','POST']])test(`Unauthenticated write: ${path} ${method}`,async()=>{const f=await fixture();assert.equal((await f.request(path,{method,data:{}})).status,401);assert.equal(f.github.calls.length,0);});
test('Session survives independent runtime; logout invalidates copied cookie',async()=>{const f=await fixture(),session=await f.login();assert.equal((await f.request('session/me',session)).status,200);const auth=createAuth(f.store,configuration(f.env));assert.equal((await auth.require(new Request('https://parafia.example',{headers:{cookie:session.cookie}}))).email,f.env.ADMIN_EMAIL);assert.equal((await f.request('logout',{...session,method:'POST',data:{}})).status,200);assert.equal((await f.request('session/me',session)).status,401);});
test('Expired session does not refresh implicitly',async()=>{const f=await fixture(),session=await f.login();f.advance(SESSION_SECONDS*1000+1);assert.equal((await f.request('session/me',session)).status,401);});
test('Rotating password hash invalidates old sessions',async()=>{const f=await fixture(),session=await f.login();f.env.ADMIN_PASSWORD_HASH=f.env.ADMIN_PASSWORD_HASH.slice(0,-1)+(f.env.ADMIN_PASSWORD_HASH.endsWith('0')?'1':'0');assert.equal((await f.request('session/me',session)).status,401);});
test('CSRF and Origin enforced; read remains available to logged-in browser',async()=>{const f=await fixture(),session=await f.login();assert.equal((await f.request('content',{cookie:session.cookie,method:'POST',data:{collection:'ogloszenia',data:notice}})).status,403);assert.equal((await f.request('content',{...session,method:'POST',origin:'https://evil.test',data:{collection:'ogloszenia',data:notice}})).status,403);assert.equal((await f.request('login',{method:'POST',origin:'null',data:{email:f.env.ADMIN_EMAIL,password:testPassword}})).status,403);assert.equal(f.github.calls.length,0);});
test('Create -> read -> edit -> conflict -> delete, Github branch and version SHA',async()=>{
  const f=await fixture(),session=await f.login();let response=await f.request('content',{...session,method:'POST',data:{collection:'ogloszenia',data:notice}});assert.equal(response.status,201);const created=await response.json();
  assert.match(created.filename,/2026-10-03-spotkanie-parafialne/);
  response=await f.request(`content?collection=ogloszenia&filename=${created.filename}`,session);assert.equal((await response.json()).data.title,notice.title);
  const path=`content/ogloszenia/${created.filename}`;const original=JSON.parse(f.github.files.get(path).bytes);f.github.seed(path,{...original,provenance:'preserve me'});const sha=f.github.files.get(path).sha;
  response=await f.request('content',{...session,method:'POST',data:{collection:'ogloszenia',filename:created.filename,sha,data:{...notice,title:'Nowy tytuł'}}});assert.equal(response.status,200);const updated=await response.json();assert.equal(JSON.parse(f.github.files.get(path).bytes).provenance,'preserve me');
  assert.equal((await f.request('content',{...session,method:'POST',data:{collection:'ogloszenia',filename:created.filename,sha,data:notice}})).status,409);
  assert.equal((await f.request('content',{...session,method:'DELETE',data:{collection:'ogloszenia',filename:created.filename,sha:updated.sha}})).status,200);assert.ok(!f.github.files.has(path));
  for(const call of f.github.calls.filter(c=>c.method!=='GET'))assert.equal(call.body.branch,'main');
});
test('Real image decode/reencode -> upload API -> GitHub -> announcement image',async()=>{
  const f=await fixture(),session=await f.login();const bytes=await sharp({create:{width:40,height:30,channels:3,background:'ivory'}}).jpeg().toBuffer();
  const response=await f.request('upload',{...session,method:'POST',bytes,type:'image/jpeg'});assert.equal(response.status,201);const result=await response.json();assert.match(result.path,/^\/assets\/uploads\/.*\.jpg$/);const uploaded=f.github.files.get(result.path.slice(1));assert.equal((await sharp(uploaded.bytes).metadata()).format,'jpeg');assert.ok(f.github.calls.at(-1).body.message.includes('[skip netlify]'));
  assert.equal((await f.request(`media?path=${encodeURIComponent(result.path)}`,session)).status,200);
  assert.equal((await f.request('content',{...session,method:'POST',data:{collection:'ogloszenia',data:{...notice,image:result.path}}})).status,201);
});
test('Upload rejects SVG, fake JPEG, oversized files and MIME mismatch',async()=>{const f=await fixture(),session=await f.login();assert.equal((await f.request('upload',{...session,method:'POST',bytes:Buffer.from('<svg/>'),type:'image/svg+xml'})).status,415);assert.equal((await f.request('upload',{...session,method:'POST',bytes:Buffer.from('<html>not a photo</html>'),type:'image/jpeg'})).status,422);assert.equal((await f.request('upload',{...session,method:'POST',bytes:Buffer.alloc(2*1024*1024+1),type:'image/png'})).status,413);const png=await sharp({create:{width:4,height:4,channels:3,background:'white'}}).png().toBuffer();assert.equal((await f.request('upload',{...session,method:'POST',bytes:png,type:'image/jpeg'})).status,422);assert.equal(f.github.calls.length,0);});
test('Images between 1 and 2 MB use GitHub raw API for reads and validation',async()=>{const f=await fixture(),session=await f.login();const bytes=await sharp(randomBytes(400*1000*3),{raw:{width:400,height:1000,channels:3}}).png().toBuffer();assert.ok(bytes.length>1024*1024 && bytes.length<2*1024*1024);const response=await f.request('upload',{...session,method:'POST',bytes,type:'image/png'});assert.equal(response.status,201);const result=await response.json();const media=await f.request(`media?path=${encodeURIComponent(result.path)}`,session);assert.equal(media.status,200);assert.ok((await media.arrayBuffer()).byteLength>1024*1024);assert.equal((await f.request('content',{...session,method:'POST',data:{collection:'ogloszenia',data:{...notice,image:result.path}}})).status,201);});
test('Concurrent panel writes are serialized and lock recovers after failure',async()=>{const f=await fixture();let release;const pending=new Promise(resolve=>{release=resolve;});const first=withWriteLock(f.store,()=>pending);await new Promise(resolve=>setTimeout(resolve,1));await assert.rejects(()=>withWriteLock(f.store,()=>Promise.resolve()),{status:409});release('ok');assert.equal(await first,'ok');await assert.rejects(()=>withWriteLock(f.store,()=>{throw new Error('test failure');}));assert.equal(await withWriteLock(f.store,()=>Promise.resolve('next')),'next');});
test('PNG and WebP upload supported',async()=>{const f=await fixture(),session=await f.login();for(const format of ['png','webp']){const bytes=await sharp({create:{width:4,height:4,channels:4,background:'transparent'}}).toFormat(format).toBuffer();assert.equal((await f.request('upload',{...session,method:'POST',bytes,type:`image/${format}`})).status,201);}});
test('Missing repository image prevents content write',async()=>{const f=await fixture(),session=await f.login();assert.equal((await f.request('content',{...session,method:'POST',data:{collection:'ogloszenia',data:{...notice,image:'/assets/uploads/missing.jpg'}}})).status,422);assert.ok(f.github.calls.every(c=>c.method==='GET'));});
test('Path traversal, collection spoofing and unknown fields blocked',async()=>{const f=await fixture(),session=await f.login();for(const path of ['../netlify.toml','..%2fconfig.json','../../x.json','a/b.json','a\\b.json']){assert.throws(()=>contentPath('ogloszenia',path));assert.equal((await f.request(`content?collection=ogloszenia&filename=${encodeURIComponent(path)}`,session)).status,400);}for(const path of ['/assets/../index.html','/assets/uploads/x.svg','https://evil.test/a.jpg','/assets/a.jpg?x=1'])assert.throws(()=>mediaPath(path));assert.throws(()=>contentPath('../netlify','a.json'));assert.throws(()=>validateContent('ogloszenia',{...notice,__secret:'bad'}));assert.equal(f.github.calls.length,0);});
test('Server validates dates, links, boolean values and intentions',()=>{assert.throws(()=>validateContent('ogloszenia',{...notice,date:'2026-02-30'}));assert.throws(()=>validateContent('ogloszenia',{...notice,published:'true'}));assert.throws(()=>validateContent('intencje',{title:'Msze',date:'2026-10-03',published:true,masses:[{time:'25:00',place:'Kościół w Kotuszowie',intention:'Intencja'}]}));assert.doesNotThrow(()=>validateContent('intencje',{title:'Msze',date:'2026-10-03',published:true,masses:[{time:'17:00',place:'Kościół w Kotuszowie',intention:'Intencja'}]}));});
test('Missing ENV fails closed and never exposes details',async()=>{const f=await fixture();delete f.env.SESSION_SECRET;const response=await f.request('session/me');assert.equal(response.status,503);assert.ok(!(await response.text()).includes('synthetic-github-token'));});
test('Distributed login throttle uses atomic writes',async()=>{const f=await fixture();for(let i=0;i<10;i++)await f.store.setJSON('unused',{i});const session=await f.login();for(let i=0;i<9;i++)assert.equal((await f.request('login',{method:'POST',data:{email:f.env.ADMIN_EMAIL,password:'bad'}})).status,401);assert.equal((await f.request('login',{method:'POST',data:{email:f.env.ADMIN_EMAIL,password:testPassword}})).status,429);f.advance(900001);assert.equal((await f.request('login',{method:'POST',data:{email:f.env.ADMIN_EMAIL,password:testPassword}})).status,200);assert.equal((await f.request('session/me',session)).status,200);});
test('Direct default function endpoint is not an alternate login route',async()=>{const f=await fixture();assert.equal((await f.handler(new Request('https://parafia.example/.netlify/functions/admin-login'))).status,404);});
