const source='https://www.szydlow.pl/10-lat-bractwa-jakubowego-w-sluzbie-spolecznosci-lokalnej/';
const credit='Fotorelacja: Michał Kaczmarczyk (wg artykułu) · jubileusz 2025';
export const additionalChurchPhotos=[
  {image:'assets/oltarz-2025.webp',alt:'Ołtarz kościoła podczas jubileuszu Bractwa w lipcu 2025',title:'Przy ołtarzu',description:'Bliższy widok prezbiterium i ołtarza podczas uroczystości jubileuszowych w lipcu 2025 r. Fotografia dokumentuje tę uroczystość, nie dzisiejsze nabożeństwo.',source,credit},
  {image:'assets/muszla-kwiaty-2025.webp',alt:'Muszla św. Jakuba w dekoracji kwiatowej przed ołtarzem',title:'Jakubowa muszla',description:'Żółta muszla wśród słoneczników — detal dekoracji świątyni przygotowanej na jubileusz Bractwa w 2025 r. Obejrzyj go z bliska.',source,credit},
  {image:'assets/chor-2025.webp',alt:'Chór muzyczny kościoła w Kotuszowie podczas uroczystości w 2025',title:'Chór muzyczny',description:'Spójrz w górę: chór muzyczny widziany od strony nawy. Zdjęcie z fotorelacji jubileuszowej z lipca 2025 r.',source,credit},
  {image:'assets/wnetrze-ku-chorowi-2025.webp',alt:'Wnętrze kościoła w Kotuszowie widziane w stronę chóru w lipcu 2025',title:'Spojrzenie ku chórowi',description:'Odwróć kierunek spojrzenia: nawa, ławki i chór od strony prezbiterium. Fotografia z nabożeństwa podczas jubileuszu w 2025 r.',source,credit},
  {image:'assets/elewacja-boczna-2025.webp',alt:'Boczna elewacja kościoła podczas procesji w lipcu 2025',title:'Dookoła kościoła',description:'Boczna elewacja i teren bezpośrednio przy świątyni, sfotografowane podczas jubileuszowej procesji w lipcu 2025 r. To kościół, nie krajobraz z innej miejscowości.',source,credit}
];
export const suppliedChurchPhotos=[
  {image:'assets/obraz-maryi-detal.webp',title:'Obraz Matki Bożej z bliska',alt:'Zbliżenie obrazu Matki Bożej z Dzieciątkiem w ołtarzu',description:'Przyjrzyj się twarzom i ozdobnej sukience obrazu. Klikaj punkty w widoku, aby obejrzeć detal lub wrócić do całego ołtarza.',credit:'Materiał przekazany przez użytkownika · autor i data niepodane'},
  {image:'assets/liturgia-przy-oltarzu.webp',title:'Przy ołtarzu — liturgia',alt:'Celebracja przy ołtarzu kościoła',description:'Ujęcie ołtarza podczas nabożeństwa. Data wydarzenia nie została podana; fotografia nie przedstawia aktualnie trwającej liturgii.',credit:'Materiał przekazany przez użytkownika · autor i data niepodane'},
  {image:'assets/nawa-organy-wspolnota.webp',title:'Nawa, organy i wspólnota',alt:'Widok nawy w kierunku chóru i organów podczas nabożeństwa',description:'Spójrz ku chórowi muzycznemu. Kliknij punkt przy organach lub wróć do widoku ołtarza.',credit:'Materiał przekazany przez użytkownika · autor i data niepodane'},
  {image:'assets/prezbiterium-front.webp',title:'Przed ołtarzem',alt:'Frontalny widok prezbiterium i ołtarza',description:'Jesteś przy prezbiterium. Punkt na obrazie prowadzi do zbliżenia, a punkt powrotu — do nawy.',source:'https://diecezjasandomierska.pl/kotuszow-sw-jakuba-starszego-apostola/',credit:'Materiał przekazany przez użytkownika · autor i data niepodane'},
  {image:'assets/kosciol-od-prezbiterium.webp',title:'Od strony prezbiterium',alt:'Bryła kościoła od strony prezbiterium i bocznej elewacji',description:'Obejrzyj świątynię z zewnątrz, a następnie wróć do wejścia, klikając punkt w fotografii.',source:'https://diecezjasandomierska.pl/kotuszow-sw-jakuba-starszego-apostola/',credit:'Materiał przekazany przez użytkownika · autor i data niepodane'}
];
